### PR TITLE
Allow FTDI devices

### PR DESCRIPTION
**Pull request by jbliesener**
This patch detects FTDI based COM ports in addition to pure Teensy devices. It doesn't yet detect physical COM ports.

### CODE REVIEW

**Comment by jbliesener** [comment]
Sorry, something went wrong here. I'll resubmit another Pull request

**Comment by jbliesener** [comment]
OK, I simply forgot to commit to master before syncing with remote. Git newbie here... Should work with commit fbe70ba

**Comment by Koromix** [comment]
I did include your commit manually, so closing the pull request. Thanks for the fix!

**Comment by Defragster** [comment]
Note from other combo issue - the FTDI needs means to init USB 'Serial' speed to actually work end to end.

I always wondered what that seemingly pointless baud dropdown was in the IDE for - it works with FTDI.

**Pull request closed without merging**
