### PR TITLE
T4 1 ms

### PR DESCRIPTION
**Pull request by KurtE**
Now that the Teensy 4.1 has released, it would be great if it had support in it for it.

Awhile ago during the beta, I made a version starting I believe from your multiple_serials branch that I believe added in this support.  

Not sure if I did it the way that you would do and/or if I would have been better to do it versus the master branch. 

But at a minimum, maybe it gives you a good starting point.

Thanks

### CODE REVIEW

**Comment by Defragster** [comment]
Hope time allows - would be great to have official build support for all platforms with T_4.1.

**Comment by Koromix** [comment]
I don't have a Teensy 4.1 board, so I can't test this. But I trust you and I've pushed this to master (with a few style fixes, hopefully that's alright).
Thanks!

**Comment by Koromix** [comment]
I've also rebased the multiple_serials branch on it. The master branch still does not have multi-serial support.

**Comment by KurtE** [comment]
Thanks!

**Comment by Defragster** [comment]
IT WORKS!

Win 10x64 - finally did Arduino integration - SO NICE!

T_4.1 upload okay and set for Triple Serial and it worked!
The next compile single Serial - the other virtual extra Serial just go (missing)

ALSO: Have an "Feather nRF52840 Express" online that works for Generic Connect!
Have to manually take Serial offline to upload - but it works for SerMon.

**Pull request closed without merging**
